name: academia_unifor
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  convex_bottom_bar: ^3.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  go_router: ^14.8.1
  http: ^1.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
    - assets/mocks/gymEquipment.json
